# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76002ca35bbeeb3930042466e8e2d9638263a54dc5a0a5e5e593ec5a8935be8b16e06f30aeab3ededdc79835dc576e823864d5e34420d8ef38b76ec4b657acf8

test:
  secret_key_base: 46c859ae1b89c0acedf1c6f76bc50104ab7bbaa6f6a64a3157369db06788507cf88d7473e0b93c1dae914a3dd2294a07862c3c407e768d7400d4f6029e4580b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
